# .github/workflows/linux.yml
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Linux Build

on:
  push:
    # branches: [ "main" ]
    paths:
      - "include/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - ".github/workflows/linux.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "include/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - ".github/workflows/linux.yml"

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false

      matrix:
        # TODO: sanitizer: [debug, release, asan, usan, tsan]
        sanitizer: [debug, release]
        compiler: [g++-14, clang++-19]

    steps:
      - uses: actions/checkout@v4

      - name: Install static analyzers
        run: >-
          sudo apt-get install clang-tidy-19 ninja-build -y -q

          sudo update-alternatives --install
          /usr/bin/clang-tidy clang-tidy
          /usr/bin/clang-tidy-19 140

      - name: Linux ${{ matrix.compiler }} ${{ matrix.sanitizer }}
        run: CXX=${{ matrix.compiler }} make ${{ matrix.sanitizer }}
