# .github/workflows/macos.yml
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Macos Build

on:
  push:
    # branches: [ "main" ]
    paths:
      - "include/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - ".github/workflows/macos.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "include/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - ".github/workflows/macos.yml"

jobs:
  build:
    runs-on: macos-15
    strategy:
      fail-fast: false

      matrix:
        sanitizer: [debug, release]
        # TODO: compiler: [g++, clang++-19]
        compiler: [g++, clang++-18]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Cpp
        # if: startsWith(matrix.compiler, 'clang')
        uses: aminya/setup-cpp@v1
        with:
          # TODO: compiler: llvm-19
          # clangtidy: true
          # cmake: true
          ninja: true

      - name: macos ${{ matrix.compiler }} ${{ matrix.sanitizer }}
        if: startsWith(matrix.compiler, 'clang')
        run: CXX=$(brew --prefix llvm@18)/bin/clang++ make ${{ matrix.sanitizer }}

      - name: macos ${{ matrix.compiler }} ${{ matrix.sanitizer }}
        if: startsWith(matrix.compiler, 'g++')
        run: CXX=${{ matrix.compiler }} make ${{ matrix.sanitizer }}
