# .github/workflows/windows.yml
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Windows Build

on:
  push:
    # branches: ["main"]
    paths:
      - "include/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - ".github/workflows/windows.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "include/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - ".github/workflows/windows.yml"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false

      matrix:
        # TODO: sanitizer: [debug, release]
        sanitizer: [release]
        # TODO: compiler: [cl, clang-cl]
        compiler: [cl]

    steps:
      - uses: actions/checkout@v4

      # see https://github.com/marketplace/actions/enable-developer-command-prompt
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: 2022

      # - name: build environment
      #   run: pip install -r requirements.txt

      - name: cmake workflow ${{ matrix.sanitizer }}
        shell: bash
        run: |
          cmake --version
          ninja --version
          CXX=${{ matrix.compiler }} cmake --workflow --preset ${{ matrix.sanitizer }}

      # - name: configure
      #   run: CXX=${{ matrix.compiler }} cmake --preset ${{ matrix.sanitizer }}

      # - name: build
      #   run: cmake --build --preset ${{ matrix.sanitizer }}

      # - name: ctest
      #   run: ctest --preset ${{ matrix.sanitizer }}
